version: '3.8'

services:
  mongo-db:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=nest-pokemon
      # - MONGODB_INIT_USER=
      # - MONGODB_INIT_PASSWORD=
    volumes:
      - ./mongo:/data/db
